// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AuthenticateUserData, AuthenticateUserResponses, ChangeAvatarData, ChangeAvatarResponses, ChangePasswordData, ChangePasswordResponses, DeleteResumeData, DeleteResumeResponses, GetCompanyProfileData, GetCompanyProfileResponses, GetJobPreferenceData, GetJobPreferenceResponses, GetMyProfileData, GetMyProfileResponses, GetMyResumesData, GetMyResumesResponses, LogoutUserData, LogoutUserResponses, RegisterUserData, RegisterUserResponses, RequestPasswordResetData, RequestPasswordResetResponses, ResetPasswordData, ResetPasswordResponses, SearchJobsData, SearchJobsResponses, UpdateJobPreferenceData, UpdateJobPreferenceResponses, UpdatePersonalInformationData, UpdatePersonalInformationResponses, UploadResumeData, UploadResumeResponses, ValidateResetTokenData, ValidateResetTokenResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getMyResumes = <ThrowOnError extends boolean = false>(options?: Options<GetMyResumesData, ThrowOnError>) => (options?.client ?? client).get<GetMyResumesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/resumes',
    ...options
});

export const uploadResume = <ThrowOnError extends boolean = false>(options: Options<UploadResumeData, ThrowOnError>) => (options.client ?? client).post<UploadResumeResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/resumes',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const deleteResume = <ThrowOnError extends boolean = false>(options: Options<DeleteResumeData, ThrowOnError>) => (options.client ?? client).delete<DeleteResumeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/resumes/{resumeId}',
    ...options
});

export const getMyProfile = <ThrowOnError extends boolean = false>(options?: Options<GetMyProfileData, ThrowOnError>) => (options?.client ?? client).get<GetMyProfileResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/profile',
    ...options
});

export const updatePersonalInformation = <ThrowOnError extends boolean = false>(options: Options<UpdatePersonalInformationData, ThrowOnError>) => (options.client ?? client).patch<UpdatePersonalInformationResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getJobPreference = <ThrowOnError extends boolean = false>(options?: Options<GetJobPreferenceData, ThrowOnError>) => (options?.client ?? client).get<GetJobPreferenceResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/job-preference',
    ...options
});

export const updateJobPreference = <ThrowOnError extends boolean = false>(options: Options<UpdateJobPreferenceData, ThrowOnError>) => (options.client ?? client).patch<UpdateJobPreferenceResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/job-preference',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const changeAvatar = <ThrowOnError extends boolean = false>(options: Options<ChangeAvatarData, ThrowOnError>) => (options.client ?? client).patch<ChangeAvatarResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/avatar',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>) => (options.client ?? client).patch<ChangePasswordResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const searchJobs = <ThrowOnError extends boolean = false>(options?: Options<SearchJobsData, ThrowOnError>) => (options?.client ?? client).get<SearchJobsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/jobs',
    ...options
});

export const getCompanyProfile = <ThrowOnError extends boolean = false>(options: Options<GetCompanyProfileData, ThrowOnError>) => (options.client ?? client).get<GetCompanyProfileResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/companies/{companyId}',
    ...options
});

export const authenticateUser = <ThrowOnError extends boolean = false>(options: Options<AuthenticateUserData, ThrowOnError>) => (options.client ?? client).post<AuthenticateUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const registerUser = <ThrowOnError extends boolean = false>(options: Options<RegisterUserData, ThrowOnError>) => (options.client ?? client).post<RegisterUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logoutUser = <ThrowOnError extends boolean = false>(options?: Options<LogoutUserData, ThrowOnError>) => (options?.client ?? client).post<LogoutUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/logout',
    ...options
});

export const requestPasswordReset = <ThrowOnError extends boolean = false>(options: Options<RequestPasswordResetData, ThrowOnError>) => (options.client ?? client).post<RequestPasswordResetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/forgot-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const resetPassword = <ThrowOnError extends boolean = false>(options: Options<ResetPasswordData, ThrowOnError>) => (options.client ?? client).post<ResetPasswordResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const validateResetToken = <ThrowOnError extends boolean = false>(options: Options<ValidateResetTokenData, ThrowOnError>) => (options.client ?? client).get<ValidateResetTokenResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/reset-password/validate',
    ...options
});
