// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type ResumeDto = {
    id: string;
    title: string;
    fileUrl: string;
    fileType: 'PDF' | 'DOC' | 'DOCX';
    fileSize: number;
    uploadedAt: string;
};

export type GetMyResumeResponse = {
    resumes: Array<ResumeDto>;
};

export type UploadResumeResponse = {
    message: string;
    resume: ResumeDto;
};

export type PersonalInformationDto = {
    fullName: string | null;
    dateOfBirth: string | null;
    headline: string | null;
    phoneNumber: string | null;
    city: string | null;
    summary: string | null;
    updatedAt: string;
};

export type UpdatePersonalInformationResponse = {
    message: string;
    userProfile: PersonalInformationDto;
};

export type UpdatePersonalInformationRequest = {
    fullName?: string;
    dateOfBirth?: string | null;
    headline?: string;
    phoneNumber?: string;
    city?: string;
    summary?: string;
};

export type ProfileVisibility = 'PRIVATE' | 'VISIBLE_TO_EMPLOYERS';

export type JobSearchStatus = 'OPEN_TO_WORK' | 'NOT_LOOKING';

export type JobPreferencesDto = {
    profileVisibility: 'VISIBLE_TO_EMPLOYERS' | 'PRIVATE';
    jobSearchStatus: 'OPEN_TO_WORK' | 'NOT_LOOKING';
    desiredJobTitle: string | null;
    preferredLocation: string | null;
    updatedAt: string;
};

export type UpdateJobPreferencesResponse = {
    message: string;
    userJobPreference: JobPreferencesDto;
};

export type UpdateJobPreferencesRequest = {
    profileVisibility?: 'VISIBLE_TO_EMPLOYERS' | 'PRIVATE';
    jobSearchStatus?: 'OPEN_TO_WORK' | 'NOT_LOOKING';
    desiredJobTitle?: string;
    preferredLocation?: string;
};

export type ChangeAvatarResponse = {
    message: string;
    avatarUrl: string;
};

export type ChangePasswordResponse = {
    message: string;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type JobListItemDto = {
    id: string;
    title: string;
    description?: string;
    employmentType: string;
    location: string;
};

export type SearchJobsResponse = {
    items: Array<JobListItemDto>;
};

export type SearchJobsQuery = {
    keyword?: string;
    location?: string;
};

export type CompanyProfileDto = {
    id: string;
    name: string;
    city: string;
    district?: string | null;
    description: string;
};

export type EmploymentType = 'ON_SITE' | 'REMOTE' | 'HYBRID';

export type CompanyJobListItemDto = {
    id: string;
    title: string;
    employmentType: EmploymentType;
    location: string;
};

export type CompanyProfileResponse = {
    company: CompanyProfileDto;
    jobs: Array<CompanyJobListItemDto>;
};

export type LoginResponse = {
    accessToken: string;
    user: {
        status: string;
        roleId: number;
        email: string;
        id: string;
    };
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type RegisterResponse = {
    user: {
        status: 'ACTIVE' | 'BANNED';
        roleId: number;
        email: string;
        id: string;
    };
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type LogoutResponse = {
    message: string;
};

export type ForgotPasswordResponse = {
    message: string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ResetPasswordResponse = {
    message: string;
};

export type ResetPasswordRequest = {
    token: string;
    newPassword: string;
};

export type GetMyResumesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/resumes';
};

export type GetMyResumesResponses = {
    /**
     * Ok
     */
    200: GetMyResumeResponse;
};

export type GetMyResumesResponse = GetMyResumesResponses[keyof GetMyResumesResponses];

export type UploadResumeData = {
    body: {
        resumeTitle: string;
        resumeFile: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/users/me/resumes';
};

export type UploadResumeResponses = {
    /**
     * Created
     */
    201: UploadResumeResponse;
};

export type UploadResumeResponse2 = UploadResumeResponses[keyof UploadResumeResponses];

export type DeleteResumeData = {
    body?: never;
    path: {
        resumeId: string;
    };
    query?: never;
    url: '/users/me/resumes/{resumeId}';
};

export type DeleteResumeResponses = {
    /**
     * OK
     */
    200: {
        message: string;
    };
};

export type DeleteResumeResponse = DeleteResumeResponses[keyof DeleteResumeResponses];

export type GetMyProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/profile';
};

export type GetMyProfileResponses = {
    /**
     * OK
     */
    200: {
        profile: {
            updatedAt: string;
            avatarUrl: string;
            city: string;
            phoneNumber: string;
            summary: string;
            headline: string;
            dateOfBirth: string;
            fullName: string;
        };
    };
};

export type GetMyProfileResponse = GetMyProfileResponses[keyof GetMyProfileResponses];

export type UpdatePersonalInformationData = {
    body: UpdatePersonalInformationRequest;
    path?: never;
    query?: never;
    url: '/users/me/profile';
};

export type UpdatePersonalInformationResponses = {
    /**
     * OK
     */
    200: UpdatePersonalInformationResponse;
};

export type UpdatePersonalInformationResponse2 = UpdatePersonalInformationResponses[keyof UpdatePersonalInformationResponses];

export type GetJobPreferenceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/job-preference';
};

export type GetJobPreferenceResponses = {
    /**
     * OK
     */
    200: {
        preference: {
            preferredLocation: string;
            desiredJobTitle: string;
            jobSearchStatus: JobSearchStatus;
            profileVisibility: ProfileVisibility;
        };
    };
};

export type GetJobPreferenceResponse = GetJobPreferenceResponses[keyof GetJobPreferenceResponses];

export type UpdateJobPreferenceData = {
    body: UpdateJobPreferencesRequest;
    path?: never;
    query?: never;
    url: '/users/me/job-preference';
};

export type UpdateJobPreferenceResponses = {
    /**
     * OK
     */
    200: UpdateJobPreferencesResponse;
};

export type UpdateJobPreferenceResponse = UpdateJobPreferenceResponses[keyof UpdateJobPreferenceResponses];

export type ChangeAvatarData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/users/me/avatar';
};

export type ChangeAvatarResponses = {
    /**
     * OK
     */
    200: ChangeAvatarResponse;
};

export type ChangeAvatarResponse2 = ChangeAvatarResponses[keyof ChangeAvatarResponses];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/users/me/change-password';
};

export type ChangePasswordResponses = {
    /**
     * OK
     */
    200: ChangePasswordResponse;
};

export type ChangePasswordResponse2 = ChangePasswordResponses[keyof ChangePasswordResponses];

export type SearchJobsData = {
    body?: never;
    path?: never;
    query?: {
        keyword?: string;
        location?: string;
    };
    url: '/jobs';
};

export type SearchJobsResponses = {
    /**
     * OK
     */
    200: SearchJobsResponse;
};

export type SearchJobsResponse2 = SearchJobsResponses[keyof SearchJobsResponses];

export type GetCompanyProfileData = {
    body?: never;
    path: {
        companyId: string;
    };
    query?: never;
    url: '/companies/{companyId}';
};

export type GetCompanyProfileResponses = {
    /**
     * OK
     */
    200: CompanyProfileResponse;
};

export type GetCompanyProfileResponse = GetCompanyProfileResponses[keyof GetCompanyProfileResponses];

export type AuthenticateUserData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthenticateUserResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type AuthenticateUserResponse = AuthenticateUserResponses[keyof AuthenticateUserResponses];

export type RegisterUserData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterUserResponses = {
    /**
     * Created
     */
    201: RegisterResponse;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type LogoutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutUserResponses = {
    /**
     * OK
     */
    200: LogoutResponse;
};

export type LogoutUserResponse = LogoutUserResponses[keyof LogoutUserResponses];

export type RequestPasswordResetData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type RequestPasswordResetResponses = {
    /**
     * OK
     */
    200: ForgotPasswordResponse;
};

export type RequestPasswordResetResponse = RequestPasswordResetResponses[keyof RequestPasswordResetResponses];

export type ResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetPasswordResponses = {
    /**
     * OK
     */
    200: ResetPasswordResponse;
};

export type ResetPasswordResponse2 = ResetPasswordResponses[keyof ResetPasswordResponses];

export type ValidateResetTokenData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/auth/reset-password/validate';
};

export type ValidateResetTokenResponses = {
    /**
     * OK
     */
    200: {
        valid: boolean;
    };
};

export type ValidateResetTokenResponse = ValidateResetTokenResponses[keyof ValidateResetTokenResponses];
