// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type LoginResponse = {
    accessToken: string;
    user: {
        status: string;
        roleId: number;
        email: string;
        id: string;
    };
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type RegisterResponse = {
    user: {
        status: string;
        roleId: number;
        email: string;
        id: string;
    };
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type LogoutResponse = {
    message: string;
};

export type ForgotPasswordResponse = {
    message: string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ResetPasswordResponse = {
    message: string;
};

export type ResetPasswordRequest = {
    token: string;
    newPassword: string;
};

export type AuthenticateUserData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthenticateUserResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type AuthenticateUserResponse = AuthenticateUserResponses[keyof AuthenticateUserResponses];

export type RegisterUserData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterUserResponses = {
    /**
     * Created
     */
    201: RegisterResponse;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type LogoutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutUserResponses = {
    /**
     * OK
     */
    200: LogoutResponse;
};

export type LogoutUserResponse = LogoutUserResponses[keyof LogoutUserResponses];

export type RequestPasswordResetData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type RequestPasswordResetResponses = {
    /**
     * OK
     */
    200: ForgotPasswordResponse;
};

export type RequestPasswordResetResponse = RequestPasswordResetResponses[keyof RequestPasswordResetResponses];

export type ResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetPasswordResponses = {
    /**
     * OK
     */
    200: ResetPasswordResponse;
};

export type ResetPasswordResponse2 = ResetPasswordResponses[keyof ResetPasswordResponses];

export type ValidateResetTokenData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/auth/reset-password/validate';
};

export type ValidateResetTokenResponses = {
    /**
     * OK
     */
    200: {
        valid: boolean;
    };
};

export type ValidateResetTokenResponse = ValidateResetTokenResponses[keyof ValidateResetTokenResponses];
